[workspace]
resolver = "2"

members = [
    "edge-frame",
    "kitchen-sink",
]

[patch.crates-io]
embedded-svc = { path = "../embedded-svc" }

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"
