[package]
name = "edge-frame"
version = "0.3.1"
authors = ["Ivan Markov <ivan.markov@gmail.com>"]
edition = "2018"
categories = ["embedded", "hardware-support", "ui"]
keywords = ["ui", "embedded", "frame", "yew", "wasm", "webpack", "svc", "hal"]
description = "Yew & Wasm-based user interface for microcontrollers."
repository = "https://github.com/ivmarkov/edge-frame"
license = "MIT OR Apache-2.0"

[lib]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true
opt-level = 'z'

[features]
# If you uncomment this line, it will enable `wee_alloc`:
#default = ["wee_alloc"]

[patch.crates-io]
#embedded-svc = { path = "../embedded-svc" }

[dependencies]
# The `wasm-bindgen` crate provides the bare minimum functionality needed
# to interact with JavaScript.
enumset = "1"
anyhow = "1"
async-trait = "*"
js-sys = "0.3"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
gloo-timers = "0.2"
yew = { version = "0.19", default-features = false }
yew-router = { version = "0.16" }
surf = {version = "*", default-features = false, features = ["wasm-client"]}
serde_json = "1"
serde = "1"
url = "2"
strum = {version = "0.23"}
getrandom = {version = "0.2", features = ["js"]}
embedded-svc = { version = "0.17.3", features = ["experimental"] }
futures = "0.3"
log = "0.4"
wasm-logger = "0.2"

# `wee_alloc` is a tiny allocator for wasm that is only ~1K in code size
# compared to the default allocator's ~10K. However, it is slower than the default
# allocator, so it's not enabled by default.
wee_alloc = {version = "0.4", optional = true}

# The `web-sys` crate allows you to interact with the various browser APIs,
# like the DOM.
[dependencies.web-sys]
version = "0.3"
features = ["console"]

# The `console_error_panic_hook` crate provides better debugging of panics by
# logging them with `console.error`. This is great for development, but requires
# all the `std::fmt` and `std::panicking` infrastructure, so it's only enabled
# in debug mode.
[target."cfg(debug_assertions)".dependencies]
console_error_panic_hook = "0.1"

# These crates are used for running unit tests.
[dev-dependencies]
wasm-bindgen-test = "0.2"
js-sys = "0.3"
wasm-bindgen-futures = "0.3"
