name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '50 4 * * *'

env:
  rust_toolchain: nightly-2022-03-23

jobs:
  compile:
    name: Compile
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
          components: rustfmt, clippy
      - name: Setup | Default to nightly
        run: rustup default ${{ env.rust_toolchain }}
      - name: Build | Fmt Check
        run: cargo fmt -- --check
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Build | Clippy
        run: cargo clippy --no-deps --target wasm32-unknown-unknown -- -Dwarnings
      - name: Build | Compile / assets-prepare
        run: cargo build --no-default-features --features assets-prepare
      - name: Build | Compile / assets-serve
        run: cargo build --no-default-features --features assets-serve
      - name: Setup | Trunk
        run: cargo install trunk
      - name: Build | Trunk
        run: cd kitchen-sink; trunk build
