name: Publish

on:
  workflow_dispatch

env:
  rust_toolchain: stable
  CRATE_NAME: edge-frame

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
      - name: Setup | Set toolchain
        run: rustup default ${{ env.rust_toolchain }}
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Login
        run: cargo login ${{ secrets.crates_io_token }}
      - name: Build | Publish
        run: cd edge-frame; cargo publish --target wasm32-unknown-unknown
      - name: Get the crate version from cargo
        run: |
          version=$(cargo metadata --format-version=1 --no-deps | jq -r ".packages[] | select(.name == \"${{env.CRATE_NAME}}\") | .version")
          echo "crate_version=$version" >> $GITHUB_ENV
          echo "${{env.CRATE_NAME}} version: $version"
      - name: Tag the new release
        uses: rickstaa/action-create-tag@v1
        with:
          tag: v${{env.crate_version}}
          message: "Release v${{env.crate_version}}"
