name: PublishDryRun

on:
  workflow_dispatch

jobs:
  publishdryrun:
    name: Publish Dry Run
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ secrets.rust_toolchain }}
      - name: Setup | Std
        run: rustup component add rust-src --toolchain nightly-x86_64-unknown-linux-gnu
      - name: Setup | Default to nightly
        run: rustup default ${{ secrets.rust_toolchain }}
      - name: Build | Publish Dry Run
        run: cd edge-frame; cargo publish --dry-run --target wasm32-unknown-unknown
