name: Publish

on:
  workflow_dispatch

env:
  rust_toolchain: nightly-2022-03-23

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.rust_toolchain }}
      - name: Setup | Default to nightly
        run: rustup default ${{ env.rust_toolchain }}
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Login
        run: cargo login ${{ secrets.crates_io_token }}
      - name: Build | Publish
        run: cd edge-frame; cargo publish --target wasm32-unknown-unknown
