name: Publish

on:
  workflow_dispatch

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2
      - name: Setup | Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ secrets.rust_toolchain }}
      - name: Setup | Default to nightly
        run: rustup default ${{ secrets.rust_toolchain }}
      - name: Login
        run: cargo login ${{ secrets.crates_io_token }}
      - name: Build | Publish
        run: cd edge-frame; cargo publish --target wasm32-unknown-unknown
